# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6665456a313dced22fd88e4cefc744e157aa65278422e50763c7c97ce08fca57a961c150b81e2bfaf077199d3a16dc93b71fd6b705f3ce60d00dfa40b292273

test:
  secret_key_base: fdbabb6195f58d61683b997b462d9af1fee8ef76c45e4898b7f1afe7550aec1ff125d15cfab258c2b7fe68174fa1b5c2bce9640666d6b98d2f993bdc244392cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
